// COUNTER
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_INCREMENT_FULFILLED = 'COUNTER_INCREMENT_FULFILLED';
export const COUNTER_GET_VALUE = 'COUNTER_GET_VALUE';
export const COUNTER_GET_VALUE_FULFILLED = 'COUNTER_GET_VALUE_FULFILLED';
export const COUNTER_COUNT_FROM_ZERO = 'COUNTER_COUNT_FROM_ZERO';
export const COUNTER_COUNT_FROM_ZERO_FULFILLED = 'COUNTER_COUNT_FROM_ZERO_FULFILLED';
export const COUNTER_GET_AVERAGE_TIME = 'COUNTER_GET_AVERAGE_TIME';
export const COUNTER_GET_AVERAGE_TIME_FULFILLED = 'COUNTER_GET_AVERAGE_TIME_FULFILLED';
export const COUNTER_GET_AVERAGE_CLICK = 'COUNTER_GET_AVERAGE_CLICK';
export const COUNTER_GET_AVERAGE_CLICK_FULFILLED = 'COUNTER_GET_AVERAGE_CLICK_FULFILLED';
export const COUNTER_GET_ALL_CLICK = 'COUNTER_GET_ALL_CLICK';
export const COUNTER_GET_ALL_CLICK_FULFILLED = 'COUNTER_GET_ALL_CLICK_FULFILLED';